server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # 开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
        - id: payment_routh  # 路由的ID，没有固定规则单要求唯一，建议配合服务名
#          uri: http://localhost:8001 # 匹配后提供服务的路由地址，
          uri: lb://cloud-payment-service  # 匹配后提供服务的路由地址，   lb表示负载均衡的功能
          predicates:
            - Path=/payment/get/**  # 断言，路径相匹配进行路由


        - id: payment_routh2 # 同上
#          uri: http://localhost:8001
          uri: lb://cloud-payment-service  # 匹配后提供服务的路由地址，
          predicates:
            - Path=/payment/lb/**
#            - Cookie=username,zzyy
#            - After=2021-01-02T15:46:26.046+08:00[Asia/Shanghai]
#            - Header=X-Request-Id,\d+ #请求头要有X-Request-Id 属性并且值为正数的正则表达式



eureka:
  instance:
    hostname: cloud-gateway-service  #eureka服务端的实例名称
  client:
    #false 代表不向注册中心注册自己
    register-with-eureka: true
    # false 表示自己就是注册中心，我的职责就是维护服务实例  并不需要去检索服务
    fetch-registry: true
    service-url:
      # 设置与eureka server交互的地址查询服务和注册服务都需要依赖这个地址
      defaultZone: http://eureka7001.com:7001/eureka/
