server:
  port: 7001
eureka:
  instance:
    hostname: eureka7001.com  #eureka服务端的实例名称
  client:
    #false 代表不向注册中心注册自己
    register-with-eureka: false
    # false 表示自己就是注册中心，我的职责就是维护服务实例  并不需要去检索服务
    fetch-registry: false
    service-url:
      # 设置与eureka server交互的地址查询服务和注册服务都需要依赖这个地址
#      defaultZone: http://eureka7002.com:7002/eureka/
#      单机版
      defaultZone: http://eureka7001.com:7001/eureka/
  server:
    # 关闭自我保护机制  保证不可用服务及时剔除   发送心跳默认90s
    enable-self-preservation: false
    #  发送心跳默认90s   自定义修改为2000
    eviction-interval-timer-in-ms: 2000
