server:
  port: 83
spring:
  application:
    name: nocas-order-consumer
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848


# 消费者将要去访问的微服务名称（注册成功nacos的微服务提供者）
service-url:
  nacos-user-service: http://nocas-payment-provider